services:
  api:
    build: 
      context: .
      target: development
    container_name: orchard-api-dev
    ports:
      - "8011:8011"
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./documents:/app/documents
      - ./app:/app/app  # Mount source code for development
      - ./plugins:/app/plugins  # Mount plugins for development
      - ./main.py:/app/main.py  # Mount main.py for development
      - ./rag_config.jsonc:/app/rag_config.jsonc  # Mount config file
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
      - OLLAMA_MODEL=llama3.1:8b
      - CHROMA_DB_PATH=/app/chroma_db
      - EMBEDDING_MODEL=all-MiniLM-L6-v2
      - CHUNK_SIZE=1000
      - CHUNK_OVERLAP=200
      - MAX_TOKENS=500
      - TEMPERATURE=0.7
      - MAX_RETRIEVED_CHUNKS=5
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - orchard-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: orchard-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
      - ./frontend/tailwind.config.js:/app/tailwind.config.js
      - ./frontend/postcss.config.js:/app/postcss.config.js
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8011
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
    depends_on:
      - api
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - orchard-network

volumes:
  chroma_db:
    driver: local
  documents:
    driver: local

networks:
  orchard-network:
    driver: bridge 