services:
  api:
    build:
      context: .
      target: development
    container_name: orchard-api-dev
    ports:
      - "8011:8011"
      - "5678:5678"  # Debugger port
    volumes:
      - ./chroma_db:/app/data/chroma_db
      - ./documents:/app/documents
      - ./model_cache:/app/data/model_cache  # Mount pre-downloaded models
      - ./app:/app/app  # Mount source code for development
      - ./plugins:/app/plugins  # Mount plugins for development
      - ./main.py:/app/main.py  # Mount main.py for development
      - ./rag_config.yaml:/app/rag_config.yaml  # Mount config file
      - ./cli:/app/cli  # Mount CLI for development
      - ./orchard_cli.py:/app/orchard_cli.py  # Mount CLI entry point
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
      - OLLAMA_MODEL=llama3.1:8b
      - CHROMA_DB_PATH=/app/data/chroma_db
      - EMBEDDING_MODEL=all-mpnet-base-v2
      - CHUNK_SIZE=1500
      - CHUNK_OVERLAP=300
      - MAX_TOKENS=500
      - TEMPERATURE=0.7
      - MAX_RETRIEVED_CHUNKS=5
      - DEBUG_MODE=${DEBUG_MODE:-false}
      - PYDEVD_DISABLE_FILE_VALIDATION=1 # Disable debugpy warning for frozen standard library modules
      # Model cache configuration for pre-downloaded models
      - TRANSFORMERS_CACHE=/app/data/model_cache
      - SENTENCE_TRANSFORMERS_HOME=/app/data/model_cache
      - HF_HOME=/app/data/model_cache
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - orchard-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: orchard-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
      - ./frontend/tailwind.config.js:/app/tailwind.config.js
      - ./frontend/postcss.config.js:/app/postcss.config.js
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8011
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
    depends_on:
      - api
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - orchard-network

volumes:
  chroma_db:
    driver: local
  documents:
    driver: local

networks:
  orchard-network:
    driver: bridge