version: '1.0'
plugins:
  github:
    enabled: false
    config:
      repositories: []
      github_token: ${GITHUB_TOKEN}
  website:
    enabled: false
    config:
      sites: []
      crawler_settings:
        max_depth: 2
        respect_robots_txt: true
        user_agent: OrchardRAG/1.0
global_settings:
  chunk_size: 1024
  chunk_overlap: 200
  batch_size: 100
  auto_sync: false
  sync_interval_hours: 24
